name = "4gaming-query"
main = "api/index.js"
compatibility_date = "2023-01-06"
[env.production]
IPI_URL="https://4gaming-query.nffigueroag.workers.dev"
ENVIRONMENT = "production"
JWT_SECRET="NO2wHnPSvXHsb8p3Rzx40G/XcCnI29H0h1CQRSW4t3lznxRa/QFlqK087OW71a5hbqzOffRbuSWr769fFKWxBaPzQH2WeQu2fdtoQLgiZwE5BuU6dtYodJFvEhKz+YPWzGtNrj008bljWcy5AaEJrfwsVfkQZn738T8uBx844ngVgkEOE2Rj7MKidvCUkqmfXCtOCJRfH8TPfjIMKHT8h32shzfoL/9vaHEsJOcsobkfbjxOK+MxFGH+4hV+yKH1+hgNwXDABkRNgZh6QY88IGbvd+QL3jStyRpsvJNPIeUrMyIVs1GWgD9Q7CerBbk5loqwQ+ywPGng/aMvZ+pEYA=="