export enum ICON_TYPE {
  LOGO = 'LogoIcon',
  STORE = 'StoreIcon',
  CLOSE = 'CloseIcon',
  ARROW_UP = 'ArrowUpIcon',
  ARROW_DOWN = 'ArrowDownIcon',
  HAMBURGER = 'HamburgerIcon',
  LOCATION = 'LocationIcon',
  LOOKUP = 'LookupIcon',
  WARNING = 'WarningIcon',
  CONTROL = 'ControlIcon',
  GAME_BOY = 'GameboyIcon',
  GAMEPAD = 'GamepadIcon',
  XBOX = 'XboxIcon',
  SONY_PS = 'SonyPlayIcon',
  LAPTOP = 'LaptopIcon',
  THUMBS_UP = 'ThumbsUpIcon',
}
