import { scrapper, scrapWebAsLists } from '../common/scrapping-strategies';
import { Store } from '../model/store';

export const SEARCH_TXT_KEYWORD = '{searchText}';

export enum STORES_LIST {
  SPEEDLOGIC = 'SpeedLogic',
  IMAGEN_WORLD = 'Imagen World',
  TIENDA_GAMER_MEDELLIN = 'Tienda Gamer Medellin',
  CLONES_Y_PERIFERICOS = 'Clones y Perifericos',
  TAURET = 'Tauret',
  MERCADO_LIBRE = 'MercadoLibre',
  GAMERS_COLOMBIA = 'Gamers Colombia',
  TRADE_INN = 'Trade Inn',
  MUNDO_COMPUTO = 'Mundo Computo Armenia',
  NUEVO_WEBO = 'Nuevo Wevo',
  MR_PC = 'Mr Pc',
  AMAZON = 'Amazon',
}
export const STORES: Store[] = [
  {
    enableScrapping: false,
    name: STORES_LIST.SPEEDLOGIC,
    urlDomain: 'https://speedlogic.com.co',
    urlStore: 'https://partes.speedlogic.com.co/',
    queryEnable: false,
    scrapper: scrapWebAsLists,
    priceMultiple: 1000,
    scrapping: {
      url: '',
      image: '',
      title: '',
      price: '',
    },
  },
  {
    name: STORES_LIST.IMAGEN_WORLD,
    enableScrapping: false,
    urlDomain: 'https://www.imagenworld.com',
    urlStore: 'https://www.imagenworld.com/xapps/listaprecios/3/a',
    queryEnable: false,
    scrapper: scrapWebAsLists,
    scrapping: {
      url: '',
      title: '',
      price: '',
      image: '',
    },
  },
  {
    name: STORES_LIST.TIENDA_GAMER_MEDELLIN,
    enableScrapping: false,
    urlDomain: 'https://www.tiendagamermedellin.co',
    urlStore: 'https://www.tiendagamermedellin.co/search?q={searchText}',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: 'div.product-block__info > a',
      image: `img[class*='product-block__image']`,
      title: 'div.product-block__info > a',
      price: `div[class*='product-block__price']`,
    },
  },
  {
    name: STORES_LIST.CLONES_Y_PERIFERICOS,
    enableScrapping: false,
    urlDomain: 'https://clonesyperifericos.com',
    urlStore:
      'https://clonesyperifericos.com/?s={searchText}&post_type=product&et_search=true',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: '.vc_custom_1644423010756 > a',
      image: `img[class*='wp-post-image']`,
      title: 'h2.product-title',
      price: 'span.woocommerce-Price-amount > bdi',
    },
  },
  {
    name: STORES_LIST.TAURET,
    enableScrapping: false,
    urlDomain: 'https://tauretcomputadores.com',
    urlStore:
      'https://tauretcomputadores.com/search_product?product_search={searchText}&product_search_slug=',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: '',
      image: 'a.image-link > img.img-fluid',
      title: 'div.name > a > h2',
      price: 'span.price1',
    },
  },
  {
    name: STORES_LIST.MERCADO_LIBRE,
    enableScrapping: false,
    urlDomain: 'https://mercadolibre.com.co',
    urlStore: 'https://listado.mercadolibre.com.co/{searchText}',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: 'a.ui-search-item__group__element',
      image: `img[class*='ui-search-result-image']`,
      title: 'h2.ui-search-item__title',
      price:
        'section > ol > li > div > div > div.ui-search-result__content-wrapper.shops__result-content-wrapper > div.ui-search-result__content-columns.shops__content-columns > div.ui-search-result__content-column.ui-search-result__content-column--left.shops__content-columns-left > div.ui-search-item__group.ui-search-item__group--price.shops__items-group > div > div > div > span.price-tag.ui-search-price__part.shops__price-part > span.price-tag-amount > span.price-tag-fraction',
    },
  },

  {
    name: STORES_LIST.GAMERS_COLOMBIA,
    enableScrapping: false,
    urlDomain: 'https://gamerscolombia.com',
    urlStore: 'https://gamerscolombia.com/tienda?productSearch={searchText}',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: 'h3.product-title > a',
      image: 'a.product-thumb > img',
      title: 'h3.product-title > a',
      price: 'h4.product-price',
    },
  },
  {
    name: STORES_LIST.TRADE_INN,
    enableScrapping: false,
    urlDomain: 'https://www.tradeinn.com',
    urlStore:
      'https://www.tradeinn.com/techinn/es?products_search%5Bquery%5D={searchText}',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: '.zona_infoprod_busca',
      image: '',
      title: 'div.hit-name',
      price: 'div.hit-price',
    },
  },
  {
    name: STORES_LIST.MUNDO_COMPUTO,
    enableScrapping: false,
    urlDomain: 'https://mundocomputo.com',
    urlStore: 'https://mundocomputo.com/shop?search={searchText}&order=',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: '',
      image: '',
      title: 'h6 > a',
      price: 'div.product_price',
    },
  },
  {
    name: STORES_LIST.NUEVO_WEBO,
    enableScrapping: false,
    urlStore: 'https://nuevowevo.com/?s={searchText}',
    urlDomain: 'https://nuevowevo.com',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: `a[class*='woocommerce-LoopProduct-link']`,
      image: `img[class*='attachment-woocommerce_thumbnail']`,
      title: 'h2.woocommerce-loop-product__title',
      price: 'span > bdi',
    },
  },
  {
    name: STORES_LIST.MR_PC,
    enableScrapping: false,
    urlStore: 'https://www.mrpc.com.co/shop/?product_cat=&s={searchText}',
    urlDomain: 'https://www.mrpc.com.co/',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: `div.product-detail-wrapper > a[href*='.com']`,
      image: `img[class*='attachment-shop-catalog']`,
      title: 'h3.product-name',
      price: `span[class*='Price-amount'] > bdi`,
    },
  },
  {
    name: STORES_LIST.AMAZON,
    enableScrapping: true,
    urlStore: 'https://www.amazon.com/s?k=${searchText}',
    urlDomain: 'https://www.amazon.com/',
    queryEnable: true,
    scrapper,
    scrapping: {
      url: `span > a[class*='a-link-normal s-no-outline']`,
      image: `span > a[class*='a-link-normal s-no-outline'] > div > img`,
      title: `a > span[class*='a-color-base a-text-normal']`,
      price: `span[class*='a-price-whole']`,
    },
  },
];
