name: Deploy to Clodflare
on:
  push:
    branches: [main]
jobs:
  deploy_api:
    if: github.repository_owner == 'nffigueroa'
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    name: API deploying
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - name: test
        run: echo 'El secreto es ${{secrets.CLOUDFLARE_APIKEY}}'
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          email: nffigueroag@gmail.com
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: api
          command: publish --env production
  build_ui:
    if: github.repository.owner == 'nffigueroa'
    runs-on: ubuntu-22.04
    name: Build UI
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18.2
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build project 
        run: pnpm build
  deploy_ui:
    if: github.repository.owner == 'nffigueroa'
    runs-on: ubuntu-22.04
    name: UI deploying
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          email: nffigueroag@gmail.com
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: api
          command: publish pages ./dist      
    
